### ISSUE TITLE
minSdk

### ISSUE THREAD

**Issue by neikila** [OlegSchwann/android-view-numbers#1]
Семестровый проект требует minSdk 21+. Пока что в крупных проектах закладываются именно на 21 по умолчанию.
Понизь, пожалуйста.

**Comment by OlegSchwann** [comment]
[Понизил минимальную версию.](https://github.com/OlegSchwann/android-view-numbers/commit/565e2f1e980c57314cc32ac90806bbf44bae8fe9)
