### ISSUE TITLE
setNumber делает много лишней работы

### ISSUE THREAD

**Issue by neikila** [OlegSchwann/android-view-numbers#2]
setNumber должен только проставлять аргументы без работы со view.
Как Я вижу твоя "оптимизация" работает в сценарии:
1) посмотреть первое число
2) вернуться
3) посмотреть второе число.
Однако, на стадии возврата твоя вьюшка уничтожается (вызывается onDestroyView)
Скажу больше, вызывается даже onDestroy
Поэтому, когда ты занова прицепишь тот же самый инстанс фрагмент у тебя снова вызовется onViewCreated и у тебя уже в настоящих вьюшках будут выставлены значения.
Поэтому попытка выставить значения в setNumber бессмыслена.

Поэтмоу же бессмыслена попытка выставить значения полей
        this.number = number;
        this.color = color;
т.к. у тебя все равно вызовется onCreate и ты перезапишешь их.

Оставь только сохранение в бандл и убери избыточную логику.

**Comment by OlegSchwann** [comment]
[Поправил.](https://github.com/OlegSchwann/android-view-numbers/commit/bd99e522c1a40b4626586dfc57df7e70b524eee5)  
Показалось, что фрагменты должны иметь большее время жизни.
