### ISSUE TITLE
onPause vs onSaveIInstanceState

### ISSUE THREAD

**Issue by neikila** [OlegSchwann/android-view-numbers#3]
Плохая практика исппользовать для сохранения состояния фрагмента onPause + setArguments.
Используй именно  onSaveInstanceState.
В противном случае ты теряешь возможность понять, что было начальным сосотоянием, а что является промежуточным значением.
Т.е. если пользователь изменил что-то вприложение, но еще не сохранил это, то ты сохранишь это как начальное состояние и потеряешь эту разницу.

Переделай на onSaveInstanceState

**Comment by OlegSchwann** [comment]
Мне, ссылаясь на доклад Yandex, советовали сохранения в onPause делать. В Yandex почте черновики сохраняются в onPause. Как выяснилось, onSaveInstanceState не корректно работает на дешёвых телефонах.
Но ок, перенесу код.

**Comment by neikila** [comment]
Можешь не переносить, главное что ты сделал это осознанно и можешь аргументировать. 
Но доклад Я бы глянул. Возможно для конкретно их задач onSaveInstanceState был непригоден. Имхо хранить набросок текст письма в bundle плохая идея в любом случае т.к. bundle ограничен в размере. И в таком случае действительно правильно в onPause сохранять черновик в базу.
Но это не то же самое что заменить аргументы.

**Comment by neikila** [comment]
Собственно вдвойне интересно, какая именно проблема с onSaveInstanceState на дешевых телефонах, потому что сдается мне, что связана она c bundle и тогда arguments могут быть ей также подвержены. Поэтому можешь полюбопыствовать у своего коллеги ссылку на доклад или детальное описание проблемы, правда интересно.

**Comment by neikila** [comment]
Поинтересовался у Андрея он помнит про onPause и у них там происходит именно сохранение в бд, что действительно логично.

Но изначально, проблему которую Я описал - это то, что ты перезаписываешь исходные параметры, что чаще всего является Bad practice (поэтому например в котлины параметры функций являются val)

**Comment by OlegSchwann** [comment]
[Перенёс.](https://github.com/OlegSchwann/android-view-numbers/commit/8b256df1155e5558f5de650a37170c211541a383)  
Спасибо, что помогли разобраться.
